### PR TITLE
Some more updates

### PR DESCRIPTION
**Pull request by crumdidlyumshis**

### CODE REVIEW

**Comment by Bunny67** [comment]
please commit
not pull requests

**Comment by crumdidlyumshis** [comment]
Oh shit sorry! I am still getting used to this. Close this if needed.

**Comment by crumdidlyumshis** [comment]
Should I close this? I am still reading about this. Sorry.

**Comment by Bunny67** [comment]
This branch cannot be rebased due to conflicts

**Comment by crumdidlyumshis** [comment]
kk, I will close it and re-commit.

**Pull request closed without merging**
