### PR TITLE
A lot of updates :)

### PR DESCRIPTION
**Pull request by crumdidlyumshis**

### CODE REVIEW

**Comment by Loaal** [comment]
I see no reason to make skin functions global

**Comment by crumdidlyumshis** [comment]
I will leave you two @Loaal and @Bunny67 to focus on the remaining stuff xD

👍

**Comment by crumdidlyumshis** [comment]
@Loaal Oh I was just doing what I saw @Bunny67 doing. I honestly don't know much about whats best in LUA. I just know the skins are the easiest for me to tackle. Do what you please :) I am just trying to help make this the best TBC addon out there for the upcoming servers 👍

**Comment by crumdidlyumshis** [comment]
I am on a roll 🍺

**Pull request merged**
