### PR TITLE
Some german translations

### PR DESCRIPTION
**Pull request by fatlus**
missing translations, typos, etc.

### CODE REVIEW

**Comment by Apollyonn** [comment]
Please remove the translations you added that wasn't there in the first place like, "Intelect", "Energy Regen" etc. some of them are not part of stock ElvUI but from other plugins like ElvUI_Enhanced.

**Comment by fatlus** [comment]
I thought they are implemented in stock ElvUI because they are already there when I disable ElvUI_Enhanced. I'll remove them but where can I find the locations of these datatexts?

**Comment by Apollyonn** [comment]
Some translations might be missing or using global strings from new expansions that don't exist at tbc, if thats the case then they need to be corrected and added to each locale file separately. Once this is done then you can translate.

**Comment by Apollyonn** [comment]
are you done with the translations? is this ready to be merged?

**Comment by fatlus** [comment]
I'll check them again after my raid

**Comment by fatlus** [comment]
Should be OK for the moment, can be merged.

**Pull request merged**
