### PR TITLE
Fix Sticky Chat - allow setting stickiness for each channel separately

### LINKED ISSUE #257: Sticky Chat dont work with Custom Channel
Normaly should the Sticky Chat option work with every channel, even with custom channel you create, but for those custom channel and officer chat it doesn't work, it just work with standard channel like /guild, /party, /raid etc.

### PR DESCRIPTION
**Pull request by Tremolo4**
The previous code in CH:ChatEdit_OnEnterPressed() apparently did nothing.

Fixes #257

### CODE REVIEW

**Comment by crumdidlyumshis** [comment]
@Tremolo4 Try latest, I think bunny fixed it. All is working on my end.

**Comment by Tremolo4** [comment]
Yes, it's working, thanks!

Although I would have liked a comment on why my version was rejected :)
Maybe because the config is simpler this way.

**Comment by Loaal** [comment]
We trying to implement same functionality as WotLK version of ElvUI has with as few changes as possible

**Comment by Tremolo4** [comment]
That makes sense. Thank you.

**Pull request closed without merging**
